# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Probe < Formula
  desc "YAML + JQ end-to-end API testing tool."
  homepage "https://github.com/abhimanyu003/probe"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_darwin_all.tar.gz"
    sha256 "4eef739ba1ed2166a91ee88133681dea6bf4c8e99434e2e80a10eff38e47cb12"

    def install
      bin.install "probe"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_linux_amd64.tar.gz"
      sha256 "b78256d1636dd06d0d1b64475d7eecb658a5fdf72fd6f7ebbf1e85f703d55fd0"

      def install
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_linux_arm64.tar.gz"
      sha256 "83be588ed030aa9e69da3263c7706205a60d0c634dd0ddffab34d87a112c5059"

      def install
        bin.install "probe"
      end
    end
  end

  test do
    system "#{bin}/probe -v"
  end
end
