# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Probe < Formula
  desc "YAML + JQ end-to-end API testing tool."
  homepage "https://github.com/abhimanyu003/probe"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_darwin_all.tar.gz"
    sha256 "23cfc848837b3075c5e5c8b3ad8d148656e4d53c73afb0856c72020928163d89"

    def install
      bin.install "probe"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_linux_amd64.tar.gz"
      sha256 "0753dff895639b4f5eb9c5052aa9535995885e02465951fa88054a8b3c6eccf0"

      def install
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.1/probe_0.0.1_linux_arm64.tar.gz"
      sha256 "3584e1edc0fbb6cadde73d96fbb40b7dc95dd02c8def5aae0430bd28ca8dc269"

      def install
        bin.install "probe"
      end
    end
  end

  test do
    system "#{bin}/probe -v"
  end
end
