# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Probe < Formula
  desc "Simplified Integration Testing Using YAML and JQ."
  homepage "https://github.com/abhimanyu003/probe"
  version "0.0.3"
  license "MIT"

  on_macos do
    url "https://github.com/abhimanyu003/probe/releases/download/v0.0.3/probe_0.0.3_darwin_all.tar.gz"
    sha256 "22d50a00ad445b30d2dfd1ae26d2021e4f0b033262aa577d2c8115d22413420e"

    def install
      bin.install "probe"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.3/probe_0.0.3_linux_amd64.tar.gz"
      sha256 "3053568eff40b834c5f90c6e1fe7ff516b59b88c992000d9553fee831d050c9f"

      def install
        bin.install "probe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/probe/releases/download/v0.0.3/probe_0.0.3_linux_arm64.tar.gz"
      sha256 "c32a282d1caf503875d6e29be0ecf67d981604323cfd5e86f8965d72f612821d"

      def install
        bin.install "probe"
      end
    end
  end

  test do
    system "#{bin}/probe -v"
  end
end
