# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pttr < Formula
  desc "A cross-platform terminal UI application for viewing and managing open ports - process on your system."
  homepage "https://github.com/abhimanyu003/pttr"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/abhimanyu003/pttr/releases/download/v0.0.1/pttr_Darwin_all.tar.gz"
    sha256 "a30afe816675f54340ca34981ff14979331d1ab16038a92744e1c30be203952e"

    def install
      bin.install "pttr"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/pttr/releases/download/v0.0.1/pttr_Linux_x86_64.tar.gz"
      sha256 "e9b41a83f0caae832527402534a2ce13cdecf8b4e20b810427d1a56dd184cbf3"
      def install
        bin.install "pttr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhimanyu003/pttr/releases/download/v0.0.1/pttr_Linux_arm64.tar.gz"
      sha256 "be368402e617c21f790df4385e4aa89b94d81488506efa9c5a1bd1e743ae8b7e"
      def install
        bin.install "pttr"
      end
    end
  end

  test do
    system "#{bin}/pttr -v"
  end
end
